### ISSUE TITLE
[feat 🔥] Search With Skills

### ISSUE THREAD

**Issue by devlopersabbir** [devlopersabbir/find-devs#11]
## Search with **name**, **locations** is already exist
So, it is better to use also Search with Skills because a user has multiple skills like `array`

In the below code, we use name & location as ilike on the `or`
```ts
db
.select()
.from(users)
.where(
    or(
         ilike(users.name, `%${searchParams}%`),
         ilike(users.location, `%${searchParams}%`),
      ),
   )
.limit(itemPerPage)
.offset(offset)
```

I would love to add documentation that will help you finish this task.
Check out this [array contains documentation](https://orm.drizzle.team/docs/operators#arraycontains)

**Comment by KambojRajan** [comment]
@jakeleventhal good evening sir.
just want to confirm what behavior is expected when 'not' gets 'undefined' as an argument?
